### ISSUE TITLE
테스트 코드 작성을 위한 리팩토링

### ISSUE THREAD

**Issue by sonmh79** [sonmh79/heart-ing#5]
# Feature Request
- Part
  - BE
- Description
  - 목적: 하트 획득 로직 테스트 코드 작성을 위해 137줄의 코드 리팩토링
  - 문제: Repository 계층과의 높은 결합도, 역할과 책임이 뚜렷하지 않은 함수
  - 해결 방법:
    1. RedisService 클래스 분리: Repository와 Service 계층으로 단일 책임을 갖는 함수로 분리 b3e6c91, 57f47e9
    2. ~~Repository계층 추상화: Repository 추상화로 JPA와 RedisTemplate을 통합하여 Service와의 의존성을 분리~~ bb61069 -> e번으로 대체
    3. 함수가 가진 두 가지 역할 분리: 파라미터(boolean)를 통해 확인과 저장 두 가지 역할을 수행할 수 있는 함수 분리 7351ead,  039ae1e
    4. Switch문 없애기: 하트 검사 추상화로 단일 책임을 가진 클래스로 나누기 d559164
    5. Facade 패턴으로 Service 계층 순환 참조 문제 해결: Service 계층이 비대해짐에 따라 역할의 모호함 + 순환 참조 문제 c7a06d8
- Deadline
  - 2024년 1월 19일

**Comment by KooooY** [comment]
리팩토링 가능하도록 리팩토링이 무슨 뜻이죠?

**Comment by sonmh79** [comment]
> 리팩토링 가능하도록 리팩토링이 무슨 뜻이죠?

리팩토링을 위한 리팩토링을 위한 리팩토링을 위한.. 무한 루프입니다
